### ISSUE TITLE
Crashes if cloud is disconnected

### ISSUE THREAD

**Issue by AmrutaCh** [jessebraham/esp32-mqtt-client#1]
ESP-IDF version: v3.1-dev-239-g1c3dd23f
Cloud: local mosquitto server

I just compiled your code fixing all dependencies issues and noticed this issue in first run itself.
If the server is closed, the application crashes saying heap corrupted.

**Comment by jessebraham** [comment]
Thanks for letting me know, I'll take a look at it after work tonight and try to get a fix pushed.

**Comment by jessebraham** [comment]
Sorry for the delay, been especially busy with work lately.

I was able to reproduce your problem, but as far as I can tell the issue seems to be upstream in the [esp32-mqtt](https://github.com/256dpi/esp-mqtt) component (or I'm missing something obvious here). I can try to get ahold of the project owner and get things sorted.
